language: java
script:
 - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/coverage-reports/jacoco/jacoco.xml -DprojectToken=CODACY_PROJECT_TOKEN -DapiToken=CODACY_PROJECT_TOKEN